

public with sharing class AS_Community_AddToBasketController {

    @AuraEnabled
    public static void addToBasket(String productId) {
//        Product2 product = new Product2(Id = productId);
//        Basket__c basket = new Basket__c(Id = 'a0K7R000012MohgUAC');
//        Product_Basket__c productBasket = new Product_Basket__c();
//        productBasket.	Product__c
//        try {
//            insert productBasket;
//        }catch (DmlException e){
//            System.debug(e);
//        }
    }

}